Bumps in ionic : ci_matching_branch/bump_ionic_gz-ionic
osrf/homebrew-simulation pull request #2463
Opened 2023-10-09 22:04 UTC by azeey

See https://github.com/gazebo-tooling/release-tools/issues/1027

2023-10-23 18:33 UTC, scpeters requested changes

2023-10-23 18:33 UTC, scpeters commented on Formula/gz-ionic.rb
> +    system libexec/"bin/vcs", "validate", "--input", yaml_file
we should change this test if we are installing release notes instead of a yaml file

2023-10-23 18:33 UTC, scpeters commented on Formula/gz-ionic.rb
> +    end
this can be removed if we don't install and test the yaml

2023-10-23 18:33 UTC, scpeters commented on Formula/gz-ionic.rb
> +  end
this can be removed if we don't install and test the yaml

2023-10-23 18:33 UTC, scpeters commented on Formula/gz-ionic.rb
> +  depends_on "python@3.11" => [:build, :test]
this can be removed if we don't install and test the yaml

2023-10-25 18:45 UTC, azeey commented
@scpeters I've addressed your feedback. I'm not sure why CI is failing though.

2023-10-30 18:55 UTC, iche033 commented
the latest brew test error could be due to having a gz-ionic file in Aliases. Let me try removing that

2023-10-30 20:18 UTC, scpeters approved these changes

2023-10-30 20:26 UTC, merged